services:
  lb:
    image: openresty/openresty:1.21.4.1-alpine
    container_name: nginx_proxy
    ports:
      - "3010:80"
    volumes:
      - ./lb/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./lb/nginx/upstreams.conf:/etc/nginx/upstreams.conf:ro
      - ./lb/nginx/conf.d/locations:/etc/nginx/conf.d/locations:ro
      - nginx_cache:/var/cache/nginx/sec_cache
    depends_on:
      - front
      - back
    networks:
      - app-network

  back:
    build:
      context: ./back
      target: development
      args:
        PORT_ARG: 4000
        NODE_VERSION: 22
    container_name: backend
    volumes:
      - ./back:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: development
      PORT: 4000
    env_file:
      - ./back/.env
    depends_on:
      - db
    networks:
      - app-network
    restart: unless-stopped

  front:
    build:
      context: ./front
      args:
        PORT: 3009
    container_name: frontend
    volumes:
      - ./front:/app
      - /app/node_modules
    ports:
      - "3009:3009"
    environment:
      - PORT=3009
      - REACT_APP_API_URL=http://localhost:4000
    networks:
      - app-network

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: canary
      POSTGRES_PASSWORD: canary
      POSTGRES_DB: db
    ports:
      - "7432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  nginx_cache:
