services:
  back:
    build:
      context: ./back
    volumes:
      - ./back:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
    depends_on:
      - db

  front:
    build:
      context: ./front
      args:
        PORT: 3009
    volumes:
      - ./front:/app
      - /app/node_modules
    ports:
      - "3009:3009"
    environment:
      - PORT=3009
      - REACT_APP_API_URL=http://localhost:4000

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: canary
      POSTGRES_PASSWORD: canary
      POSTGRES_DB: db
    ports:
      - "7432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
